[[shades]]
name = "vibrance"
default = true        # will be activated when no other shader is scheduled
[shades.config]
type = "luminosity"
luminosity_type = "hdr"
strength = 1.0

#[[shades]]
#name = "blue-light-filter"
#start_time = 19:00:00
#end_time = 06:00:00   # optional if more than one shader has start_time
